# Generated by Django 6.0.1 on 2026-01-08 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minister_tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('general_tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('thanksgiving', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('others', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sunday_school', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('children', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Financial',
            },
        ),
    ]
