# Generated by Django 6.0.1 on 2026-01-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
