# Generated by Django 6.0.1 on 2026-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_financial_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='breakthrough',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
