# Generated by Django 6.0.1 on 2026-01-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_financial_breakthrough_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
